config/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include("django.contrib.auth.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailing.apps import MailingConfig
from mailing.views import client_views, message_views, mailing_views, blog_views, main_views, mailing_attempts_views

app_name = MailingConfig.name

urlpatterns = [
    path('', main_views.MainView.as_view(), name='main'),

    path('clients/', client_views.ClientsView.as_view(), name='clients'),
    path('clients/create/', client_views.ClientCreateView.as_view(), name='create_client'),
    path('clients/update/<int:pk>', client_views.ClientUpdateView.as_view(), name='update_client'),
    path('clients/delete/<int:pk>', client_views.ClientDeleteView.as_view(), name='delete_client'),

    path('messages/', message_views.MessagesView.as_view(), name='messages'),
    path('messages/create/', message_views.MessageCreateView.as_view(), name='create_message'),
    path('messages/update/<int:pk>', message_views.MessageUpdateView.as_view(), name='update_message'),
    path('messages/delete/<int:pk>', message_views.MessageDeleteView.as_view(), name='delete_message'),

    path('mailings/', mailing_views.MailingsView.as_view(), name='mailings'),
    path('mailings/create/', mailing_views.MailingCreateView.as_view(), name='create_mailing'),
    path('mailings/update/<int:pk>', mailing_views.MailingUpdateView.as_view(), name='update_mailing'),
    path('mailings/delete/<int:pk>', mailing_views.MailingDeleteView.as_view(), name='delete_mailing'),

    path('mailing_attempts/', mailing_attempts_views.MailingAttemptsView.as_view(), name='mailing_attempts'),

    path('blog/', cache_page(60)(blog_views.BlogView.as_view()), name='blog'),
    path('blog/create_post/', blog_views.BlogPostCreateView.as_view(), name='create_post'),
    path('blog/post/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         cache_page(60)(blog_views.BlogPostDetailView.as_view()), name='post'),
    path('blog/update_post/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         blog_views.BlogPostUpdateView.as_view(), name='update_post', ),
    path('blog/delete_post/<int:year>/<int:month>/<int:day>/<slug:slug>/',
         blog_views.BlogPostDeleteView.as_view(), name='delete_post'),

]

users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from users.apps import UsersConfig
from users import views as custom_views
app_name = UsersConfig.name

urlpatterns = [
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', custom_views.RegisterView.as_view(), name='register'),
    path('profile/', custom_views.ProfileView.as_view(), name='profile'),
    path('confirm_email/<int:pk>', custom_views.ConfirmPage.as_view(), name='confirm_email'),

    path('reset_password/', auth_views.PasswordResetView.as_view(), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
   ]

mailing/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

from users.models import User


class Client(models.Model):
    # Клиент сервиса

    name = models.CharField(max_length=100,
                            verbose_name='ФИО')
    email = models.EmailField(verbose_name='Почта')
    comment = models.TextField(verbose_name='Комментарий')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', null=True)

    def __str__(self):
        return f'Клиент: {self.name}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('name',)


class Message(models.Model):
    # Сообщение для рассылки

    title = models.CharField(max_length=250,
                             verbose_name='Тема')
    body = models.TextField(default=None,
                            verbose_name='Сообщение')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', null=True)

    def __str__(self):
        return f'Тема сообщения: {self.title}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'
        ordering = ('title',)


class Mailing(models.Model):
    # Рассылка

    class Status(models.TextChoices):  # подкласс для выбора статуса рассылки
        COMPLETED = 'CM', 'completed'  # устанавливается после завершения
        CREATED = 'CR', 'created'  # устанавливается после создания
        LAUNCHED = 'LA', 'launched'  # устанавливается при запуске

    class Frequency(models.TextChoices):  # подкласс для выбора периодичности
        ONCE_A_DAY = 'DA', 'ежедневно'
        ONCE_A_WEEK = 'WE', 'еженедельно'
        ONCE_A_MONTH = 'MO', 'ежемесячно'

    time = models.TimeField(default=timezone.now,
                            verbose_name='Время начала рассылки, (чч:мм:сс)')
    date = models.DateField(default=timezone.now,
                            verbose_name='Дата следующей рассылки, (дд.мм.гггг)')
    frequency = models.CharField(max_length=2,
                                 choices=Frequency.choices,
                                 default=Frequency.ONCE_A_DAY,
                                 verbose_name='Периодичность рассылки')
    status = models.CharField(max_length=2,  # статус
                              choices=Status.choices,
                              default=Status.CREATED,
                              verbose_name='Статус рассылки')
    is_active = models.BooleanField(default=True, verbose_name='Разрешение рассылки')
    message = models.ForeignKey(Message,
                                on_delete=models.CASCADE,
                                verbose_name='Сообщение')
    clients = models.ManyToManyField(Client,
                                     verbose_name='Клиенты',
                                     related_name='mailing')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='Владелец', null=True)

    def get_label(self, frequency):
        for label in self.Frequency.choices:
            if label[0] == frequency: return label[1]

    def __str__(self):
        return f'Рассылка в {self.time} с {self.date.strftime("%d.%m.%Y")}, {self.get_label(self.frequency)}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('-time',)


class MailingLogs(models.Model):
    # Лог попытки рассылки

    time = models.DateTimeField(verbose_name='Дата и время последней рассылки')
    status = models.BooleanField()
    server_request = models.CharField(max_length=250,
                                      verbose_name='Ответ сервера')

    class Meta:
        verbose_name = 'Попытка рассылки'
        verbose_name_plural = 'Попытки рассылки'
        ordering = ('-time',)


class Post(models.Model):
    # Статья блога

    title = models.CharField(max_length=255,
                             verbose_name='Заголовок')
    slug = models.CharField(max_length=255,
                            unique_for_date='created',
                            verbose_name='Слаг')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blog/',
                                verbose_name='Изображение')
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Дата создания')
    published = models.BooleanField(default=False,
                                    verbose_name='Признак публикации')
    views = models.PositiveIntegerField(default=0,
                                        verbose_name='Количество просмотров')

    def add_view(self):
        self.views += 1
        return self.views

    def delete(self, *args, **kwargs):
        self.published = False
        self.save()

    def __str__(self):
        return f'{self.title}'

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ('-created',)

mailing/views/blog_views.py
from django.contrib.auth import mixins
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views import generic

from mailing.forms import BlogForm
from mailing.models import Post


class BlogPostCreateView(mixins.PermissionRequiredMixin, generic.CreateView):
    permission_required = 'mailing.add_post'
    model = Post
    form_class = BlogForm
    template_name = 'mailing/form.html'
    success_url = reverse_lazy('mailing:blog')
    extra_context = {
        'title': 'Создание статьи'
    }

    def form_valid(self, form):
        if form.is_valid:
            fields = form.save(commit=False)
            string = fields.title.translate(
                str.maketrans("абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
                              "abvgdeejzijklmnoprstufhzcss_y_euaABVGDEEJZIJKLMNOPRSTUFHZCSS_Y_EUA"))
            fields.slug = slugify(string)
            fields.save()
        return super().form_valid(form)


class BlogView(generic.ListView):
    model = Post
    template_name = 'mailing/blog.html'
    extra_context = {
        'title': 'Блог'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(published=True)
        return queryset


class BlogPostDetailView(generic.DetailView):
    model = Post

    def get_object(self, queryset=None):  # добавление одного просмотра
        post = super().get_object()
        post.add_view()
        post.save()
        return post

    def get_context_data(self, **kwargs):  # получение 'title'
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Просмотр статьи'
        return context_data


class BlogPostUpdateView(mixins.PermissionRequiredMixin, generic.UpdateView):
    permission_required = 'mailing.change_post'
    model = Post
    form_class = BlogForm
    template_name = 'mailing/form.html'

    extra_context = {
        'title': 'Изменить статью'
    }

    def get_success_url(self):
        return reverse('mailing:post', args=[*self.kwargs.values()])


class BlogPostDeleteView(mixins.PermissionRequiredMixin, generic.DeleteView):
    permission_required = 'mailing.delete_post'
    model = Post
    template_name = 'mailing/confirm_delete.html'
    extra_context = {
        'title': 'Удаление'
    }
    success_url = reverse_lazy('mailing:blog')

mailing/views/client_views.py
from django.urls import reverse_lazy, reverse
from django.views import generic

from mailing.forms import ClientForm
from mailing.models import Client
from mailing.views.mailing_views import SetUserMixin, EditCheckMixin


class ClientCreateView(SetUserMixin, generic.CreateView):
    form_class = ClientForm
    template_name = 'mailing/form.html'
    success_url = reverse_lazy('mailing:clients')
    extra_context = {
        'title': 'Создание клиента рассылки'
    }


class ClientsView(generic.ListView):
    model = Client
    template_name = 'mailing/clients_list.html'
    extra_context = {
        'title': 'Клиенты для рассылки'
    }


class ClientDeleteView(EditCheckMixin, generic.DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:clients')
    template_name = 'mailing/confirm_delete.html'
    extra_context = {
        'title': 'Удалить клиента'
    }


class ClientUpdateView(EditCheckMixin, generic.UpdateView):
    model = Client
    form_class = ClientForm
    template_name = 'mailing/form.html'
    extra_context = {
        'title': 'Изменить данные клиента'
    }

    def get_success_url(self):
        return reverse('mailing:clients')

mailing/views/mailing_attempts_views.py
from django.views import generic

from mailing.models import MailingLogs


class MailingAttemptsView(generic.ListView):
    model = MailingLogs
    template_name = 'mailing/mailing_attempts.html'
    extra_context = {
        'title': 'Завершенные рассылки'
    }

mailing/views/mailing_views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views import generic
from mailing import models
from mailing import forms


class EditCheckMixin:
    # проверка пользователя на автора или суперюзера
    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if self.object.user != self.request.user and not self.request.user.is_superuser:
            raise Http404('Изменять может только владелец')
        return self.object


class SetUserMixin:
    # заполнение поля 'user' модели текущим пользователем
    def form_valid(self, form):
        self.object = form.save()
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)


class PermissionAndLoginRequiredMixin(PermissionRequiredMixin, LoginRequiredMixin):
    model = models.Mailing


class MailingCreateView(PermissionRequiredMixin, SetUserMixin, generic.CreateView):
    permission_required = 'mailing.add_mailing'
    form_class = forms.MailingForm
    template_name = 'mailing/form.html'

    success_url = reverse_lazy('mailing:mailings')
    extra_context = {
        'title': 'Создание рассылки'
    }


class MailingsView(generic.ListView):
    model = models.Mailing
    template_name = 'mailing/mailings_list.html'
    extra_context = {
        'title': 'Рассылки',
    }


class MailingDeleteView(PermissionAndLoginRequiredMixin, EditCheckMixin, generic.DeleteView):
    permission_required = 'mailing.delete_mailing'
    success_url = reverse_lazy('mailing:mailings')
    template_name = 'mailing/confirm_delete.html'
    extra_context = {
        'title': 'Удалить рассылку'
    }


class MailingUpdateView(PermissionAndLoginRequiredMixin, EditCheckMixin, generic.UpdateView):
    permission_required = 'mailing.change_mailing'
    form_class = forms.MailingForm
    template_name = 'mailing/form.html'
    extra_context = {
        'title': 'Изменить данные рассылки'
    }

    def get_success_url(self):
        return reverse('mailing:mailings')

mailing/views/main_views.py
from django.views import generic

from mailing.models import Client, Mailing, Post
from mailing.services import get_posts_cached


class MainView(generic.TemplateView):
    template_name = 'mailing/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Главная страница'
        context['mailings_total'] = Mailing.objects.count()
        context['mailings_active'] = Mailing.objects.filter(is_active=True).count()
        unique_clients = []
        for client in Client.objects.all():
            if client.mailing.count() == 1:
                unique_clients.append(client.name)
        context['unique_clients'] = ', '.join(unique_clients)
        context['posts'] = get_posts_cached(3)

        return context

mailing/views/message_views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy, reverse
from django.views import generic

from mailing.forms import MessageForm
from mailing.models import Message
from mailing.views.mailing_views import SetUserMixin, EditCheckMixin


class MessageCreateView(PermissionRequiredMixin, SetUserMixin, generic.CreateView):
    permission_required = 'mailing.add_message'
    form_class = MessageForm
    template_name = 'mailing/form.html'
    success_url = reverse_lazy('mailing:messages')
    extra_context = {
        'title': 'Создание сообщения'
    }


class MessagesView(generic.ListView):
    model = Message
    template_name = 'mailing/messages_list.html'
    extra_context = {
        'title': 'Сообщения'
    }


class MessageDeleteView(PermissionRequiredMixin, EditCheckMixin, generic.DeleteView):
    permission_required = 'mailing.delete_mailing'
    model = Message
    success_url = reverse_lazy('mailing:messages')
    template_name = 'mailing/confirm_delete.html'
    extra_context = {
        'title': 'Удалить сообщение'
    }


class MessageUpdateView(PermissionRequiredMixin, EditCheckMixin, generic.UpdateView):
    permission_required = 'mailing.change_message'
    model = Message
    form_class = MessageForm
    template_name = 'mailing/form.html'
    extra_context = {
        'title': 'Изменить сообщение'
    }

    def get_success_url(self):
        return reverse('mailing:messages')

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<div class="container text-primary">
    <div class="row">
        <div class="col offset-2 d-flex justify-content-center text-info">
            <h2>{{ title }}</h2>
        </div>
    </div>
    <br>
    <div class="container">
        <div class="row">
            <div class="col-2">
                <ul class="nav flex-column h5">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:main' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:clients' %}">Клиенты</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'mailing:mailings' %}">Рассылки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'mailing:mailing_attempts' %}">Завершенные рассылки</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:messages' %}">Сообщения</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'mailing:blog' %}">Блог</a>
                    </li>
                    <li>
                        <hr style="border: 1px solid green;">
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <span class="badge badge-pill badge-primary">{{ user }}</span>
                            <a class="nav-link" href="{% url 'users:logout' %}">Выйти</a>
                            <a class="nav-link" href="{% url 'users:profile' %}">Профиль</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'users:login' %}">Войти</a>
                        {% endif %}
                    </li>

                </ul>
            </div>


            <div class="col-10">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>

mailing/templates/mailing/blog.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4">
                {% if perms.mailing.add_post %}
                    <a href='{% url 'mailing:create_post' %}' class="btn btn-primary btn-block"> Написать статью </a>
                {% endif %}
            </div>
        </div>
    </div>
    {% for post in object_list %}
        <div class="col-md-12">
            <div class="card m-2 box-shadow text-primary">
                <div class="card-body">
                    <div class="card-title">
                        <h4>{{ post }}</h4>
                    </div>
                    <p class="card-text m-1">
                    <h5><p class="card-text text-info">{{ post.content|truncatewords:10 }}</p></h5>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href='{% url 'mailing:post' post.created.year post.created.month post.created.day post.slug %}'
                               class="btn btn-outline-primary">Перейти к статье</a>

                            {% if perms.mailing.change_post %}
                                <a href='{% url 'mailing:update_post' post.created.year post.created.month post.created.day post.slug %}'
                                   class="btn btn-outline-primary">Редактировать</a>
                            {% endif %}

                            {% if perms.mailing.delete_post %}
                                <a href='{% url 'mailing:delete_post' post.created.year post.created.month post.created.day post.slug %}'
                                   class="btn btn-outline-primary">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <h6> Просмотры: {{ post.views }}</h6>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

mailing/templates/mailing/clients_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-lg-center">
            <div class="col-4">
                {% if perms.mailing.add_client %}
                    <a href='{% url 'mailing:create_client' %}' class="btn btn-primary btn-block">Добавить клиента</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% for client in object_list %}
        <div class="col-md-12">
            <div class="card m-2 box-shadow text-primary">
                <div class="card-body">
                    <h4>{{ client }}</h4>
                    <h5><p class="card-text text-info">О клиенте: {{ client.comment|truncatewords:10 }}</p></h5>
                    <h6><p class="card-text text-info">Почта клиента: {{ client.email }}</p></h6>
                    <div class="btn-group">
                        {% if client.user == request.user or request.user.is_superuser %}
                            <a href='{% url 'mailing:update_client' client.id %}'
                               class="btn btn-outline-primary">Редактировать</a>
                            <a href='{% url 'mailing:delete_client' client.id %}'
                               class="btn btn-outline-primary">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

mailing/templates/mailing/confirm_delete.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <form method="POST" , enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <h4><p class="text text-danger"> {{ object }}</h4>
                <input type="submit" class="btn btn-danger" value="Подтверждаю удаление">
            </form>
        </div>
    </div>
{% endblock %}

mailing/templates/mailing/form.html
{% extends 'mailing/base.html' %}
{% block content %}

<div class="container">
    <div class="row justify-content-center">
            <div class="col-10">

        <div class="card">
            <div class="card-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_div }}
                    <button type="submit" class="btn btn-primary"> {% if object %}Изменить{% else %}
                        Создать{% endif %}</button>
                </form>
            </div>
        </div>
        </div>
    </div>
</div>

{% endblock %}

mailing/templates/mailing/mailing_attempts.html
{% extends 'mailing/base.html' %}
{% block content %}

    {% for log in object_list %}
        <div class="col-md-12">
            <div class="card box-shadow text-primary">
                <div class="card-body">
                    <h6>{{ log.time }}</h6>
                    <h6>{{ log.server_request }}</h6>
                </div>
            </div>
        </div>
    {% endfor %}


{% endblock %}

mailing/templates/mailing/mailings_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4">
                {% if perms.mailing.add_mailing %}
                    <a href='{% url 'mailing:create_mailing' %}' class="btn btn-primary btn-block">Добавить рассылку</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% for mailing in object_list %}
        <div class="col-md-12">
            <div class="card m-2 box-shadow text-primary">
                <div class="card-body">
                    <h4>{{ mailing }}</h4>
                    <h5><p class="card-text text-info">{{ mailing.message }}</p></h5>
                    {% for client in mailing.clients.all %}
                        <h6><p class="card-text text-info">{{ client }}</p></h6>
                    {% endfor %}
                    <div class="btn-group">
                        {% if mailing.user == request.user or request.user.is_superuser %}
                            <a href='{% url 'mailing:update_mailing' mailing.id %}'
                               class="btn btn-outline-primary">Редактировать</a>
                            <a href='{% url 'mailing:delete_mailing' mailing.id %}'
                               class="btn btn-outline-primary">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

mailing/templates/mailing/main.html
{% extends 'mailing/base.html' %}
{% block content %}

    <h4><p class="text text-primary"> Всего рассылок: {{ mailings_total }}</h4>
    <h4><p class="text text-success"> Активных рассылок: {{ mailings_active }}</h4>
    {% if unique_clients %}
        <h4><p class="text text-primary"> Уникальные клиенты: {{ unique_clients }}</h4>
    {% else %}
        <h4><p class="text text-secondary"> Уникальные клиенты отсутствуют</h4> {% endif %}

    {% for post in posts %}
        <div class="col-md-12">
            <div class="card mb-4 box-shadow text-primary m-2">
                <div class="card-body">
                    <div class="card-title">
                        <h4>{{ post }}</h4>
                    </div>
                    <p class="card-text m-1">
                    <h5><p class="card-text text-info">{{ post.content|truncatewords:10 }}</p></h5>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href='{% url 'mailing:post' post.created.year post.created.month post.created.day post.slug %}'
                               class="btn btn-outline-primary">Перейти к статье</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}




{% endblock %}

mailing/templates/mailing/messages_list.html
{% extends 'mailing/base.html' %}
{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-4">
                {% if perms.mailing.add_message %}
                    <a href='{% url 'mailing:create_message' %}' class="btn btn-primary btn-block">Добавить
                        сообщение</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% for message in object_list %}
        <div class="col-md-12">
            <div class="card m-2 box-shadow text-primary">
                <div class="card-body">
                    <h5>{{ message }}</h5>
                    <h4><p class="card-text text-info">Сообщение: {{ message.body|truncatewords:50 }}</p></h4>

                    <div class="btn-group">
                        {% if message.user == request.user or request.user.is_superuser %}
                            <a href='{% url 'mailing:update_message' message.id %}'
                               class="btn btn-outline-primary">Редактировать</a>
                            <a href='{% url 'mailing:delete_message' message.id %}'
                               class="btn btn-outline-primary">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

mailing/templates/mailing/post_detail.html
{% extends 'mailing/base.html' %}
{#{% load custom_tags %}#}
{% block content %}
    <div class="album py-5 bg-light bg-transparent">
        <div class="container">
            <div class="row">
                <div class="col-md-7">
                    <div class="card mb-4 box-shadow">
                        <div class="card-body">
                            <h4><p class="card-title text-primary"> {{ object.title }}</h4>
                            <p class="card-text">{{ object.content }}</p>
                            <p class="card-footer text-info">Дата создания: {{ object.created }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <img class="card-img-top" src='{{  object.preview.url }}' alt="Card image cap">
                </div>
            </div>
        </div>
    </div>

{% endblock %}